### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#45]
This issue consolidates in a single location todo that were originally listed in #36 and #38 (later superseded by #43):

From #36 and #38:
- [x] Extend testing coverage to include the new apps and new features.
- [x] Currently the only way to add to the Cython module search path for `add_cython_target` is to use the outdated `include_directories` CMake command.  Ideally, we would be able to use `target_include_directories` or something similar.  This may involve the creation of an actual CMake target. This is now tracked in https://github.com/scikit-build/scikit-build/issues/243
- [x] There is a bug when trying to specify the desired CMake build type via the `--build-type` option in scikit-build.  It seems that some sections of the code are looking for `CMAKE_BUILD_DIR/CMAKE_BUILD_TYPE` as the ultimate location of the cmake build directory.  I think handling multiple builds in one tree is desirable and we should probably extend this handling to the other temporary staging directories, but right now, these improvements were not expecting this.  We'll need to go through the various code sections and make sure everyone's on the same page.
- [x] Refactor the custom distutils command subclasses so that they are accessible for other packages -- in case they want to work around us just as we did distutils.
- [x] Restore the default handling of generic data files so that it matches up with distutils' default behavior.  To handle stand-alone extension modules, we'll need to add extra handling logic for the `py_modules` argument; we would list these modules under `py_modules`, and leave it to scikit-build to recognize them and place them accordingly.
- [x] Add a final check to the manifest processing loop so that skbuild refuses to handle files installed outside of the project root.
- [x] Add option to the `add_cython_target` function to override the variable name used to store the location to the generated source file.
- [x] Remove TODO note in `add_cython_target` regarding C vs C++ output.  So far, no problems have been encountered one way or the other during development and testing.
- [x] Remove the FindDebugger.cmake file (used just for debugging cmake targets).
- [x] Update the `python_modules_header` function so that the `FORWARD_DECL_MODULES_VAR` option is renamed to `FORWARD_DECL_MODULES_LIST` and that the list in question is passed by value.
- [x] Add option to the `python_modules_header` function to override the variable names used to store the locations of the generated header file as well as that of the directory containing it.
- [x] Clean up tower-of-babel boost module header files.  Use `tbabel_boost_common.h` to minimize code duplication.
- [x] Projects that attempt to CMake-install files outside of its designated project installation root should fail to install.
  - [x] Ideally, they should fail prior to the CMake-install step (i.e.: before any problematic files are actually installed).  This will need code to determine the would-be files without the aid of the install manifest.
- [x] Each of the sample projects should have their own tests to at least ensure that they build correctly, and that any produced applications run without issue.
- [x] Add tests for pen2_cython
- [x] Add tests for tower-of-babel
- [x] There are multiple bugs in the way command line arguments are processed and forwarded in scikit-build.  It's not clear if they were introduced by these changes, or if they predate them.
  - [x] On a related note, I tried to pass options directly to CMake through scikit-build using the `--` argument seperator.  Scikit-build is currently written to expect up to three sections of such options: the first for scikit-build options, the second for CMake config options, and the third for options to the build step.  However, since CMake is used to drive the build step, options meant for the actual build tool (e.g.: make) must be separated by another `--` separator.  Currently scikit-build fails to properly handle this fourth separator.

**Comment by jcfr** [comment]
> CMAKE_BUILD_DIR/CMAKE_BUILD_TYPE as the ultimate location of the cmake build directory. 

`CMAKE_BUILD_TYPE` could be passed using -DCMAKE_BUILD_TYPE:STRING=Release
See http://scikit-build.readthedocs.io/en/latest/usage.html#command-line-options

> I think handling multiple builds in one tree is desirable 

For now, we delegate the handling of multiple tree to the user (e.g by calling `setup.py clean` between build) and to CMake through the use of `ExternalProject` module.

That said, adding a scikit-build option allowing to add a prefix to `_skbuild` directory (e.g `_skbuild_python_35`) is totally possible. This is now captured in https://github.com/scikit-build/scikit-build/issues/242
